import type { LifeArea, Mode } from './types';

export interface SeedHabit {
  name: string;
  icon: { ios: string; android: string; web: string };
  color: string;
  mode: Mode;
  targetPerDay: number;
  lifeArea: LifeArea;
  /** Display order within mode (lower = earlier in the day). */
  sortOrder: number;
}

/**
 * Home mode: ordered routine. "No phone usage" replaces limited phone + reels + social apps.
 * Legacy template names are removed in DB migration `home_routine_v3`.
 */
export const homeRoutineHabitsV3: SeedHabit[] = [
  {
    name: 'Fajr',
    icon: { ios: 'sunrise.fill', android: 'wb-twilight', web: 'wb-twilight' },
    color: '#4ADE80',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 10,
  },
  {
    name: 'Surah Yaseen (after Fajr)',
    icon: { ios: 'book.closed.fill', android: 'menu-book', web: 'menu-book' },
    color: '#FBBF24',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 20,
  },
  {
    name: 'Quran (morning)',
    icon: { ios: 'book.fill', android: 'menu-book', web: 'menu-book' },
    color: '#2DD4BF',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 30,
  },
  {
    name: 'Morning walk',
    icon: { ios: 'figure.walk', android: 'directions-walk', web: 'directions-walk' },
    color: '#22D3EE',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 40,
  },
  {
    name: 'Breakfast',
    icon: { ios: 'fork.knife', android: 'restaurant', web: 'restaurant' },
    color: '#F59E0B',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 50,
  },
  {
    name: 'Youth Club — 1 scholar video',
    icon: { ios: 'play.rectangle.fill', android: 'play-circle', web: 'play-circle' },
    color: '#60A5FA',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 60,
  },
  {
    name: 'Rest',
    icon: { ios: 'bed.double.fill', android: 'hotel', web: 'hotel' },
    color: '#94A3B8',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 70,
  },
  {
    name: 'Family time (no loneliness)',
    icon: { ios: 'person.3.fill', android: 'groups', web: 'groups' },
    color: '#A78BFA',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 80,
  },
  {
    name: 'Zuhr',
    icon: { ios: 'sun.max.fill', android: 'wb-sunny', web: 'wb-sunny' },
    color: '#4ADE80',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 90,
  },
  {
    name: 'Lunch',
    icon: { ios: 'takeoutbag.and.cup.and.straw.fill', android: 'lunch-dining', web: 'lunch-dining' },
    color: '#F97316',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 100,
  },
  {
    name: 'Nap',
    icon: { ios: 'moon.zzz.fill', android: 'bedtime', web: 'bedtime' },
    color: '#818CF8',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 110,
  },
  {
    name: 'Asr',
    icon: { ios: 'sun.haze.fill', android: 'wb-twilight', web: 'wb-twilight' },
    color: '#4ADE80',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 120,
  },
  {
    name: 'Afternoon walk',
    icon: { ios: 'figure.walk.motion', android: 'directions-walk', web: 'directions-walk' },
    color: '#34D399',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 130,
  },
  {
    name: 'Maghrib',
    icon: { ios: 'sunset.fill', android: 'wb-twilight', web: 'wb-twilight' },
    color: '#4ADE80',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 140,
  },
  {
    name: 'Read a book',
    icon: { ios: 'books.vertical.fill', android: 'auto-stories', web: 'auto-stories' },
    color: '#C084FC',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 150,
  },
  {
    name: 'Isha',
    icon: { ios: 'moon.stars.fill', android: 'nights-stay', web: 'nights-stay' },
    color: '#4ADE80',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 160,
  },
  {
    name: 'Dinner',
    icon: { ios: 'fork.knife.circle.fill', android: 'dinner-dining', web: 'dinner-dining' },
    color: '#FB923C',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 170,
  },
  {
    name: 'Surah Mulk',
    icon: { ios: 'moon.fill', android: 'nightlight', web: 'nightlight' },
    color: '#818CF8',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 180,
  },
  {
    name: 'Sleep before 10 pm',
    icon: { ios: 'bed.double.fill', android: 'hotel', web: 'hotel' },
    color: '#6366F1',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 190,
  },
  {
    name: 'No phone usage',
    icon: { ios: 'iphone.slash', android: 'phonelink-off', web: 'phonelink-off' },
    color: '#EF4444',
    mode: 'home',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 200,
  },
];

const hostelHabits: SeedHabit[] = [
  {
    name: 'No Explicit Content',
    icon: { ios: 'shield.checkmark.fill', android: 'shield', web: 'shield' },
    color: '#EF4444',
    mode: 'hostel',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 10,  
  },
  {
    name: 'Office Work',
    icon: { ios: 'brain.head.profile.fill', android: 'psychology', web: 'psychology' },
    color: '#A78BFA',
    mode: 'hostel',
    targetPerDay: 1,
    lifeArea: 'work',
    sortOrder: 20,
  },
  {
    name: 'No phone usage',
    icon: { ios: 'iphone.slash', android: 'phonelink-off', web: 'phonelink-off' },
    color: '#F59E0B',
    mode: 'hostel',
    targetPerDay: 1,
    lifeArea: 'mental',
    sortOrder: 30,
  },
  {
    name: 'Namaz',
    icon: { ios: 'moon.stars.fill', android: 'self_improvement', web: 'self_improvement' },
    color: '#4ADE80',
    mode: 'hostel',
    targetPerDay: 5,
    lifeArea: 'spiritual',
    sortOrder: 40,
  },
  {
    name: 'Quran',
    icon: { ios: 'book.fill', android: 'menu-book', web: 'menu-book' },
    color: '#2DD4BF',
    mode: 'hostel',
    targetPerDay: 1,
    lifeArea: 'spiritual',
    sortOrder: 50,
  },
  {
    name: 'Exercise',
    icon: { ios: 'dumbbell.fill', android: 'fitness_center', web: 'fitness_center' },
    color: '#22D3EE',
    mode: 'hostel',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 60,
  },
  {
    name: 'Walk',
    icon: { ios: 'figure.walk', android: 'directions-walk', web: 'directions-walk' },
    color: '#34D399',
    mode: 'hostel',
    targetPerDay: 1,
    lifeArea: 'physical',
    sortOrder: 70,
  },
  {
    name: 'Study Blocks',
    icon: { ios: 'clock.badge.checkmark.fill', android: 'schedule', web: 'schedule' },
    color: '#60A5FA',
    mode: 'hostel',
    targetPerDay: 3,
    lifeArea: 'work',
    sortOrder: 80,
  },
];

/** Names removed from Home when migrating from the old template (replaced by v3 routine). */
export const legacyHomeHabitNames = [
  'No Explicit Content',
  'Limited Phone Usage',
  'No Social Apps',
  'No Reels',
  'Avoid Screens Weekend',
  'Namaz',
  'Quran Reading',
  'Morning Surah Yaseen',
  'Night Surah Mulk',
  'Sleep Before 12',
  'Light Exercise',
] as const;

export const defaultHabits: SeedHabit[] = [...homeRoutineHabitsV3, ...hostelHabits];
